name: 'Upload to bucket'
description: 'Upload files to a specified bucket, optionally removing stale directories'
inputs:
  path:
    description: "What to upload. Path contents will be uploaded, not the path literally"
    required: true
  namespace:
    description: 'A part of directory name where the files will be uploaded, e.g. 20250925-namespace'
    required: true
  bucket_name:
    description: 'GCS bucket where the files will be uploaded, without gs:// or trailing slash'
    required: true
  service_account:
    description: 'Service account used for bucket upload'
    required: true
  workload_identity_provider:
    description: 'Workload Identity Provider used for authentication'
    required: true

outputs:
  path:
    description: 'Where the files have been uploaded'
    value: ${{ steps.upload-to-gcs.outputs.path }}

runs:
  using: composite
  steps:
    - name: Sanity checks
      shell: bash
      env:
        NAMESPACE: ${{ inputs.namespace }}
      run: |
        set -euo pipefail
        
        if [[ $NAMESPACE == *' '* ]]; then
          echo "Namespace cannot contain space"
          exit 1
        fi

    - uses: google-github-actions/auth@v3.0.0
      with:
        token_format: access_token
        service_account: ${{ inputs.service_account }}
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
    - id: upload-to-gcs
      shell: bash
      env:
        PATH_TO_UPLOAD: ${{ inputs.path }}
        BUCKET_NAME: ${{ inputs.bucket_name }}
        NAMESPACE: ${{ inputs.namespace }}
      run: |
        set -euo pipefail
        
        # Remember - this format is used for lexicographical comparison
        # This means that when sorted in ascending order, it should list from oldest to newest
        # Keep in sync with delete-from-bucket/action.yml
        date_format='%Y%m%d-%H%M%S'
        namespace_dir="$(date "+${date_format}")_${NAMESPACE}"

        path="/${namespace_dir}/"
        echo "path=${path}" >>$GITHUB_OUTPUT

        echo "::group::Copying files to ${namespace_dir}"
        (cd "${PATH_TO_UPLOAD}" && gcloud storage cp --recursive . "gs://${BUCKET_NAME}/${namespace_dir}/")
        echo "::endgroup::"

branding:
  color: red
  icon: arrow-up-circle
